public enum EffectType
{
    Test,
    StunNormal,
    Warp,
    Tutankhamen,
    Explosion,
    LondonTelephoneStart,
    LondonTelephoneActive,
    PtrFireMuzzle,
    PtrFireBullet,
    PtrFireExplosion,
    NormalInteractComplete,
    CooldownRect,
    CooldownSquare,
    CooldownLine,
    PunchImpact,
    OpticalCamouflageInteractComplete,
}
