//勝手にEnumを消すな！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！
public enum EffectType
{
    Test,
    Warp,
    Tutankhamen,
    Explosion,
    LondonTelephoneStart,
    LondonTelephoneActive,
    PtrFireMuzzle,
    PtrFireBullet,
    PtrFireExplosion,
    NormalInteractComplete,
    CooldownRect,
    CooldownSquare,
    CooldownLine,
    PunchImpact,
    OpticalCamouflageInteractComplete,
    StunNormal,
    CarHit,
    Heal,
    HitNormal,
    WarpIn,
    WarpOut,
    Muramasa
}
//勝手にEnumを消すな！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！
